
    drop table Regatta if exists;

    create table Regatta (
        id decimal(13,0) generated by default as identity,
        buoyages integer not null,
        end_date timestamp,
        finished boolean not null,
        name varchar(255) not null unique,
        short_name varchar(255) not null unique,
        skippers integer not null,
        start_date timestamp,
        primary key (id)
    );
